### ISSUE TITLE
Install Zopfli untuk Gzip

### ISSUE THREAD

**Issue by bangden07** [aldhinya/rochman.id#1]
Saran saya untuk gatsby install Zopfli. Zopfli sama seperti gzip sebagai kompresi file.

```
12:35:12 PM: success Zopfli compression - 54.106s -  83/83
12:35:12 PM: info Zopfli compression total payload reduced 2 MB
```

Lumayan bisa reduce sampe 2MB.

[Selengkapnya - Gatsby Plugin Zopfli](https://www.gatsbyjs.org/packages/gatsby-plugin-zopfli/)

**Comment by aldhinya** [comment]
Siap, akan saya coba, terima kasih sarannya 😁😁
